name: GitHub Actions Demo
on:
  push:
    branches: [ main ]
    paths-ignore: [ .github/** ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The job was triggered by event: ${{ github.event_name }}"
          echo "The name of your branch is ${{ github.ref }} and your repository is ."

      - uses: actions/checkout@v3.3.0

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree

  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Test
    steps:
      - run: |
          echo "Testing the build"

  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Load-Test
    steps:
      - run: |
          echo "Load-Testing the build"
          sleep 15

  Production:
    if: github.event.inputs.environment == 'Production
    runs-on: ubuntu-latest
    needs: [ Test, Load-Test ]
    environment:
      name: Production
      url: https://writeabout.net
    steps:
      - run: |
          echo "Running Step 1 in Production"
          sleep 10
      - run: |
          echo "Running Step 2 in Production"
          sleep 10
      - run: |
          echo "Running Step 3 in Production"
          sleep 10
      - run: |
          echo "Running Step 4 in Production"
          sleep 10
      - run: |
          echo "Running Step 5 in Production"
          sleep 10
